// <auto-generated />
using System;
using InterSim.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace InterSim.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260310140521_AddAnswerEvaluationSamples")]
    partial class AddAnswerEvaluationSamples
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("InterSim.Domain.Entities.Answer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AnswerText")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("BreakdownJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("DeficitsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EvaluatorVersion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("FeedbackBundleId")
                        .HasColumnType("uuid");

                    b.Property<string>("FeedbackEngineVersion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FeedbackItemsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("InterviewSessionId")
                        .HasColumnType("uuid");

                    b.Property<int>("MaxScore")
                        .HasColumnType("integer");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("Score")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("InterviewSessionId");

                    b.ToTable("answers", (string)null);
                });

            modelBuilder.Entity("InterSim.Domain.Entities.AnswerEvaluationSample", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AnswerText")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("HumanImpactReflection")
                        .HasColumnType("integer");

                    b.Property<int>("HumanRelevance")
                        .HasColumnType("integer");

                    b.Property<int>("HumanSpecificity")
                        .HasColumnType("integer");

                    b.Property<int>("HumanStructure")
                        .HasColumnType("integer");

                    b.Property<int>("HumanTotalScore")
                        .HasColumnType("integer");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("WordCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Category", "Topic", "Difficulty");

                    b.ToTable("answer_evaluation_samples", (string)null);
                });

            modelBuilder.Entity("InterSim.Domain.Entities.InterviewSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.ToTable("interview_sessions", (string)null);
                });

            modelBuilder.Entity("InterSim.Domain.Entities.QuestionBankItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsTemplate")
                        .HasColumnType("boolean");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Topic", "Difficulty", "Category");

                    b.ToTable("question_bank_items", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Category = "technical",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Difficulty = "junior",
                            IsActive = true,
                            IsTemplate = false,
                            Text = "Explain dependency injection in .NET. Why is it useful?",
                            Topic = "dotnet"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Category = "technical",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Difficulty = "junior",
                            IsActive = true,
                            IsTemplate = false,
                            Text = "What is the difference between Task and Thread in C#?",
                            Topic = "dotnet"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Category = "technical",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Difficulty = "junior",
                            IsActive = true,
                            IsTemplate = false,
                            Text = "Explain ACID. Give a practical example where it matters.",
                            Topic = "sql"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            Category = "behavioral",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Difficulty = "junior",
                            IsActive = true,
                            IsTemplate = false,
                            Text = "Tell me about a time you had a conflict in a team and how you handled it.",
                            Topic = "behavioral"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            Category = "behavioral",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Difficulty = "junior",
                            IsActive = true,
                            IsTemplate = false,
                            Text = "Describe a situation where you showed initiative to solve a problem.",
                            Topic = "behavioral"
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            Category = "behavioral",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Difficulty = "junior",
                            IsActive = true,
                            IsTemplate = false,
                            Text = "Tell me about a time you failed and what you learned from it.",
                            Topic = "behavioral"
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777777"),
                            Category = "behavioral",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Difficulty = "junior",
                            IsActive = true,
                            IsTemplate = false,
                            Text = "Describe a time when you had to learn something quickly.",
                            Topic = "behavioral"
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888888"),
                            Category = "behavioral",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Difficulty = "junior",
                            IsActive = true,
                            IsTemplate = false,
                            Text = "Tell me about a time you helped a teammate succeed.",
                            Topic = "behavioral"
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-999999999999"),
                            Category = "behavioral",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Difficulty = "junior",
                            IsActive = true,
                            IsTemplate = false,
                            Text = "Describe a time you improved a process or workflow.",
                            Topic = "behavioral"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Category = "behavioral",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Difficulty = "junior",
                            IsActive = true,
                            IsTemplate = false,
                            Text = "Tell me about a time you had to meet a tight deadline.",
                            Topic = "behavioral"
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            Category = "behavioral",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Difficulty = "junior",
                            IsActive = true,
                            IsTemplate = false,
                            Text = "Describe a situation where you received critical feedback. How did you respond?",
                            Topic = "behavioral"
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            Category = "behavioral",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Difficulty = "junior",
                            IsActive = true,
                            IsTemplate = false,
                            Text = "Tell me about a time you had to prioritize multiple tasks.",
                            Topic = "behavioral"
                        },
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            Category = "behavioral",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Difficulty = "junior",
                            IsActive = true,
                            IsTemplate = false,
                            Text = "Describe a difficult problem you solved.",
                            Topic = "behavioral"
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            Category = "behavioral",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Difficulty = "junior",
                            IsActive = true,
                            IsTemplate = false,
                            Text = "Tell me about a time you disagreed with a team decision.",
                            Topic = "behavioral"
                        },
                        new
                        {
                            Id = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff"),
                            Category = "behavioral",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Difficulty = "junior",
                            IsActive = true,
                            IsTemplate = false,
                            Text = "Describe a time you worked under pressure.",
                            Topic = "behavioral"
                        },
                        new
                        {
                            Id = new Guid("10101010-1010-1010-1010-101010101010"),
                            Category = "behavioral",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Difficulty = "junior",
                            IsActive = true,
                            IsTemplate = false,
                            Text = "Tell me about a time you made a mistake in a project.",
                            Topic = "behavioral"
                        },
                        new
                        {
                            Id = new Guid("12121212-1212-1212-1212-121212121212"),
                            Category = "behavioral",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Difficulty = "junior",
                            IsActive = true,
                            IsTemplate = false,
                            Text = "Describe a time you explained something complex to someone else.",
                            Topic = "behavioral"
                        },
                        new
                        {
                            Id = new Guid("13131313-1313-1313-1313-131313131313"),
                            Category = "behavioral",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Difficulty = "junior",
                            IsActive = true,
                            IsTemplate = false,
                            Text = "Tell me about a time you took responsibility for a difficult task.",
                            Topic = "behavioral"
                        },
                        new
                        {
                            Id = new Guid("14141414-1414-1414-1414-141414141414"),
                            Category = "behavioral",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Difficulty = "junior",
                            IsActive = true,
                            IsTemplate = false,
                            Text = "Describe a time you had to adapt to a change during a project.",
                            Topic = "behavioral"
                        },
                        new
                        {
                            Id = new Guid("15151515-1515-1515-1515-151515151515"),
                            Category = "behavioral",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Difficulty = "junior",
                            IsActive = true,
                            IsTemplate = false,
                            Text = "Tell me about a time you collaborated with someone difficult.",
                            Topic = "behavioral"
                        },
                        new
                        {
                            Id = new Guid("16161616-1616-1616-1616-161616161616"),
                            Category = "behavioral",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Difficulty = "junior",
                            IsActive = true,
                            IsTemplate = false,
                            Text = "Describe a time you solved an unexpected issue during development.",
                            Topic = "behavioral"
                        },
                        new
                        {
                            Id = new Guid("17171717-1717-1717-1717-171717171717"),
                            Category = "behavioral",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Difficulty = "junior",
                            IsActive = true,
                            IsTemplate = false,
                            Text = "Tell me about a time you supported a teammate who was struggling.",
                            Topic = "behavioral"
                        },
                        new
                        {
                            Id = new Guid("18181818-1818-1818-1818-181818181818"),
                            Category = "behavioral",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Difficulty = "junior",
                            IsActive = true,
                            IsTemplate = false,
                            Text = "Describe a time you had to make a decision with incomplete information.",
                            Topic = "behavioral"
                        });
                });

            modelBuilder.Entity("InterSim.Domain.Entities.SessionQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("GeneratedText")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("InterviewSessionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("QuestionBankItemId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("QuestionBankItemId");

                    b.HasIndex("InterviewSessionId", "QuestionBankItemId")
                        .IsUnique();

                    b.ToTable("session_questions", (string)null);
                });

            modelBuilder.Entity("InterSim.Domain.Entities.Answer", b =>
                {
                    b.HasOne("InterSim.Domain.Entities.InterviewSession", "InterviewSession")
                        .WithMany("Answers")
                        .HasForeignKey("InterviewSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InterviewSession");
                });

            modelBuilder.Entity("InterSim.Domain.Entities.SessionQuestion", b =>
                {
                    b.HasOne("InterSim.Domain.Entities.InterviewSession", "InterviewSession")
                        .WithMany("Questions")
                        .HasForeignKey("InterviewSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InterSim.Domain.Entities.QuestionBankItem", "QuestionBankItem")
                        .WithMany()
                        .HasForeignKey("QuestionBankItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("InterviewSession");

                    b.Navigation("QuestionBankItem");
                });

            modelBuilder.Entity("InterSim.Domain.Entities.InterviewSession", b =>
                {
                    b.Navigation("Answers");

                    b.Navigation("Questions");
                });
#pragma warning restore 612, 618
        }
    }
}
